#!/usr/bin/ruby

begin
  require 'hirb'
  Hirb.enable
rescue LoadError
  puts "Warning: Gem hirb not found."
end

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end

# show log as default. can't call show_log yet because ActiveRecord has not been loaded
require 'logger'
Object.const_set(:RAILS_DEFAULT_LOGGER, Logger.new(STDOUT))

